- name: Bootstrap
  hosts: all
  become: true
  roles:
    - rmb938.bootstrap

- name: Hashicorp Vault
  hosts: all
  become: true
  roles:
    - vault

- name: Init Vault
  hosts: init_server
  become: true
  roles:
    - init
