- name: Bootstrap
  hosts: all
  become: true
  vars:
    step_ca_url: https://cuboid-topi.rmb1993-gmail-com.ca.smallstep.com
  roles:
    - rmb938.bootstrap

- name: Hashicorp Vault
  hosts: all
  become: true
  roles:
    - vault
