---
- name: Create datavg
  community.general.lvg:
    vg: data
    pvs: /dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_drive-scsi1

- name: Create vault lv
  community.general.lvol:
    vg: data
    lv: vault
    size: 95G

- name: Format vault lv
  community.general.filesystem:
    fstype: xfs
    dev: /dev/data/vault

- name: Mount vault drive
  ansible.posix.mount:
    path: /opt/vault/data
    src: /dev/data/vault
    fstype: xfs
    boot: true
    state: mounted

# TODO: vault raft storage says to disable swap https://developer.hashicorp.com/vault/docs/configuration/storage/raft
#   unsure what kind of security disk that poses if we don't disable it, we will circle back to disabling it later
- name: Install TPM2 Tools & Libs
  ansible.builtin.package:
    name:
      - libtss2-dev
      - tpm2-tools
    state: present

- name: Setup SystemD Creds With Host+TPM2
  ansible.builtin.command: "systemd-creds setup --with-key=host+tpm2"
  args:
    creates: "/var/lib/systemd/credential.secret"

- name: Install Hashicorp keyring
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    checksum: sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029
    mode: "0644"

- name: Add Hashicorp repo
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc]
      https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present

- name: Install Hashicorp Vault
  ansible.builtin.package:
    name: vault
    state: present

- name: Bootstrap step cli
  ansible.builtin.command: >-
    step ca bootstrap --ca-url https://step-ca-ra.rmb938.me \
      --fingerprint eb136a5118931a2306964469705323521dda8c43d26ec67e1c5508eb123f9c70
  args:
    creates: /etc/step/config/defaults.json
  environment:
    STEPPATH: /etc/step

- name: Create Vault Certificates
  ansible.builtin.command: >-
    step ca certificate {{ ansible_fqdn }} /opt/vault/tls/vault.crt /opt/vault/tls/vault.key --san {{ inventory_hostname }}
  args:
    creates: "/opt/vault/tls/vault.crt"
  environment:
    STEPPATH: "/etc/step"

- name: Own Vault certificates
  ansible.builtin.file:
    path: /opt/vault/tls/{{ item }}
    owner: vault
    group: vault
    mode: "0600"
  with_items:
    - vault.crt
    - vault.key

- name: Cron to renew vault certificates
  ansible.builtin.cron:
    name: "renew vault certificates"
    special_time: "hourly"
    job: >-
      STEPPATH=/etc/step step ca renew /opt/vault/tls/vault.crt /opt/vault/tls/vault.key
      --force --mtls=false --expires-in 720h --exec "systemctl reload vault"
    state: present

- name: Create vault systemd override folder
  ansible.builtin.file:
    path: /etc/systemd/system/vault.service.d/
    state: directory
    mode: "0755"

- name: Vault systemd Override
  ansible.builtin.template:
    src: etc/systemd/system/vault.service.d/override.conf
    dest: /etc/systemd/system/vault.service.d/override.conf
    mode: "0644"
  register: vault_systemd_override

- name: Reload vault systemd # noqa: no-handler
  ansible.builtin.systemd:
    daemon_reload: true
  when: vault_systemd_override.changed

- name: Configure Vault
  ansible.builtin.template:
    src: etc/vault.d/vault.hcl
    dest: /etc/vault.d/vault.hcl
    mode: "0644"
  register: vault_config

- name: Start and enable Vault
  ansible.builtin.systemd:
    name: vault
    state: started
    enabled: true

- name: Restart vault if config changed # noqa: no-handler
  ansible.builtin.systemd:
    name: vault
    state: restarted
  when: vault_config.changed or vault_systemd_override.changed
