---
# TODO: vault raft storage says to disable swap https://developer.hashicorp.com/vault/docs/configuration/storage/raft
#   unsure what kind of security disk that poses if we don't disable it, we will circle back to disabling it later
- name: Install TPM2 Tools & Libs
  ansible.builtin.package:
    name:
      - libtss2-dev
      - tpm2-tools
    state: present

- name: Setup SystemD Creds With Host+TPM2
  ansible.builtin.command: "systemd-creds setup --with-key=host+tpm2"
  args:
    creates: "/var/lib/systemd/credential.secret"

- name: Install Hashicorp keyring
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    checksum: sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029
    mode: "0644"

- name: Add Hashicorp repo
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc]
      https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present

- name: Install Hashicorp Vault
  ansible.builtin.package:
    name: vault
    state: present

- name: Create Vault Certificates
  ansible.builtin.command: "step ca certificate {{ ansible_fqdn }} /etc/ssl/private/step-ca/vault.crt /etc/ssl/private/step-ca/vault.crt.key --san {{ inventory_hostname }}" # noqa: yaml[line-length]
  args:
    creates: "/etc/ssl/private/step-ca/vault.crt"
  environment:
    STEPPATH: "/etc/step"

- name: Copy Vault Certificates
  ansible.builtin.copy:
    remote_src: true
    src: /etc/ssl/private/step-ca/vault.{{ item }}
    dest: /opt/vault/tls/vault.{{ item }}
    owner: vault
    group: vault
    mode: "0600"
  with_items:
    - "crt"
    - "crt.key"

- name: Create step certs systemd override folder
  ansible.builtin.file:
    path: /etc/systemd/system/step-cert-renewer.service.d/
    state: directory
    mode: "0755"

- name: Step cert renewer systemd Override
  ansible.builtin.template:
    src: etc/systemd/system/step-cert-renewer.service.d/override.conf
    dest: /etc/systemd/system/step-cert-renewer.service.d/override.conf
    mode: "0644"
  register: cert_renewer_systemd_override

- name: Reload cert renewer systemd # noqa: no-handler
  ansible.builtin.systemd:
    daemon_reload: true
  when: cert_renewer_systemd_override.changed

- name: Create vault systemd override folder
  ansible.builtin.file:
    path: /etc/systemd/system/vault.service.d/
    state: directory
    mode: "0755"

- name: Vault systemd Override
  ansible.builtin.template:
    src: etc/systemd/system/vault.service.d/override.conf
    dest: /etc/systemd/system/vault.service.d/override.conf
    mode: "0644"
  register: vault_systemd_override

- name: Reload vault systemd # noqa: no-handler
  ansible.builtin.systemd:
    daemon_reload: true
  when: vault_systemd_override.changed

- name: Configure Vault
  ansible.builtin.template:
    src: etc/vault.d/vault.hcl
    dest: /etc/vault.d/vault.hcl
    mode: "0644"
  register: vault_config

- name: Start and enable Vault
  ansible.builtin.systemd:
    name: vault
    state: started
    enabled: true

- name: Restart vault if config changed # noqa: no-handler
  ansible.builtin.systemd:
    name: vault
    state: restarted
  when: vault_config.changed or vault_systemd_override.changed
