---
# TODO: CIS benchmark fixing once it's released for 24.04

# TODO: covert bootstrap steps to own role, see https://ruan.dev/blog/2022/04/19/publish-and-use-your-ansible-role-from-git
## START BOOTSTRAP
- name: Set timezone
  community.general.timezone:
    name: America/Chicago

- name: Configure Auto Upgrades
  ansible.builtin.template:
    src: etc/apt/apt.conf.d/50unattended-upgrades
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: "0644"
  register: unattended_upgrades_50

- name: Restart unattended-upgrades # noqa: no-handler
  ansible.builtin.systemd:
    name: unattended-upgrades
    state: restarted
  when: unattended_upgrades_50.changed

- name: Install tools
  ansible.builtin.package:
    name:
      - net-tools
      - htop
    state: present
## END BOOTSTRAP

- name: Install Hashicorp keyring
  ansible.builtin.get_url:
    url: https://apt.releases.hashicorp.com/gpg
    dest: /usr/share/keyrings/hashicorp-archive-keyring.asc
    checksum: sha256:cafb01beac341bf2a9ba89793e6dd2468110291adfbb6c62ed11a0cde6c09029
    mode: "0644"

- name: Add Hashicorp repo
  ansible.builtin.apt_repository:
    repo: >
      deb [arch=amd64 signed-by=/usr/share/keyrings/hashicorp-archive-keyring.asc]
      https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main
    state: present

- name: Install Hashicorp Vault
  ansible.builtin.package:
    name: vault
    state: present

- name: Generate tailscale certificates
  ansible.builtin.command:
    cmd: >
      /usr/bin/tailscale cert
      --cert-file /opt/vault/tls/{{ inventory_hostname }}.crt
      --key-file /opt/vault/tls/{{ inventory_hostname }}.key
      {{ inventory_hostname }}
    creates: /opt/vault/tls/{{ inventory_hostname }}.crt

- name: Own tailscale certificates to vault
  ansible.builtin.file:
    path: "{{ item }}"
    owner: vault
    group: vault
  with_items:
    - "/opt/vault/tls/{{ inventory_hostname }}.crt"
    - "/opt/vault/tls/{{ inventory_hostname }}.key"

- name: Cronjob to renew tailscale certificates
  ansible.builtin.cron:
    name: Renew tailscale Vault certificates
    special_time: daily
    job: >
      /usr/bin/tailscale cert
      --cert-file /opt/vault/tls/{{ inventory_hostname }}.crt
      --key-file /opt/vault/tls/{{ inventory_hostname }}.key
      {{ inventory_hostname }} &&
      /usr/bin/chown vault:vault /opt/vault/tls/{{ inventory_hostname }}.crt /opt/vault/tls/{{ inventory_hostname }}.key &&
      /usr/bin/systemctl reload vault
