name: Ansible Run

on:
  push:
    branches:
      - master

jobs:
  run:
    name: Ansible Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Tailscale
        uses: tailscale/github-action@v1
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: 1.28.0

      - name: Run Ansible
        run: |
          ansible-playbook -i hosts site.yaml
